import type { Metadata } from 'next';
import Link from 'next/link';
import { HeroEstimateForm } from '../components/HeroEstimateForm';

export const metadata: Metadata = { title: 'Free Roof Inspection Request', description: 'Prepare a free North Atlanta roof inspection request with service, roof, address, contact, and optional roof photo details.' };

export default function FreeInspectionPage() {
  return <main className="inspection-page"><section className="inspection-hero"><div className="inspection-copy"><p className="eyebrow light">FREE INSPECTION · OWN PROJECT FILE</p><h1>Start with<br/>real roof facts.</h1><p>Tell us the property, roof, and concern. The prototype checks the brief before you choose whether to email or call the team.</p><div className="inspection-rules"><span><b>01</b>NO SILENT UPLOAD</span><span><b>02</b>HUMAN CONFIRMATION</span><span><b>03</b>NO COVERAGE PROMISES</span></div></div><HeroEstimateForm /></section><section className="inspection-expect shell"><header><p className="eyebrow">WHAT HAPPENS NEXT</p><h2>One request.<br/>Four clean handoffs.</h2></header><div>{[['01','ROUTE','Match the concern, property, timing, and service area.'],['02','CONFIRM','A team member confirms availability and the appointment window.'],['03','INSPECT','Document roof zones, details, drainage, attic clues, and property constraints.'],['04','EXPLAIN','Receive the observed conditions, options, scope logic, and next decision.']].map(([n,title,copy]) => <article key={n}><small>{n}</small><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="inspection-links"><div className="shell"><Link href="/library/inspection-checklist"><small>OPEN THE FILE</small><b>INSPECTION CHECKLIST</b><span>→</span></Link><Link href="/roof-repair"><small>ACTIVE PROBLEM</small><b>ROOF REPAIR</b><span>→</span></Link><Link href="/storm-damage"><small>WEATHER EVENT</small><b>STORM DAMAGE</b><span>→</span></Link></div></section></main>;
}
