'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';

type Inputs={age:number;issue:string;material:string;slope:string;attic:string;property:string;priority:string;horizon:string};
const defaults:Inputs={age:17,issue:'planning',material:'shingle',slope:'standard',attic:'hot',property:'home',priority:'value',horizon:'long'};
const choices={issue:[['planning','Planning ahead'],['active','Active leak'],['recurring','Recurring leak'],['storm','Storm concern'],['wear','Widespread wear']],material:[['shingle','Asphalt shingle'],['metal','Metal'],['tile','Tile / slate'],['membrane','Low-slope membrane'],['unknown','Not sure']],slope:[['standard','Standard'],['steep','Steep / complex'],['low','Low slope'],['mixed','Mixed slopes']],attic:[['clear','No known signal'],['hot','Runs very hot'],['moisture','Moisture / odor'],['unknown','Not inspected']],property:[['home','Home'],['estate','Estate / complex'],['commercial','Commercial']],priority:[['value','Overall value'],['storm','Storm resilience'],['longevity','Longest-life path'],['design','Premium appearance'],['efficiency','Heat performance']],horizon:[['short','Under 5 years'],['medium','5–12 years'],['long','12+ years']]};
const systemBase=[{id:'architectural',name:'Impact-rated architectural shingle',fit:'North Atlanta all-rounder',copy:'Balanced value, dimensional appearance, and a familiar complete-system path.',path:'/library/architectural-shingle-system'},{id:'designer',name:'Designer laminated shingle',fit:'Premium roofline',copy:'Heavier dimensional character for prominent homes and complex elevations.',path:'/library/designer-shingles'},{id:'metal',name:'24-gauge standing seam metal',fit:'Long-life system',copy:'Concealed-fastener metal with transition, clip, penetration, and thermal-movement planning.',path:'/library/standing-seam-metal'},{id:'membrane',name:'High-performance membrane',fit:'Low-slope specialist',copy:'Continuous low-slope protection selected around drainage, seams, penetrations, and traffic.',path:'/library/low-slope-membranes'}];

export function AdvancedRoofAdvisor(){
 const [input,setInput]=useState<Inputs>(defaults);const [view,setView]=useState<'decision'|'systems'|'brief'>('decision');const [saved,setSaved]=useState(false);const [copied,setCopied]=useState(false);
 const update=(key:keyof Inputs,value:string|number)=>{setInput((now)=>({...now,[key]:value}));setSaved(false);setCopied(false)};
 const result=useMemo(()=>{
  let replace=0;const reasons:string[]=[];const flags:string[]=[];
  if(input.age>=22){replace+=42;reasons.push('Age is in a range where broad system wear deserves replacement planning.')}else if(input.age>=15){replace+=24;reasons.push('Age supports inspection and budgeting even if the roof is still serviceable.')}else{replace+=8;reasons.push('Age alone does not point strongly toward replacement.')}
  if(input.issue==='wear'){replace+=34;reasons.push('Widespread wear favors a system-level decision over isolated repair.')}if(input.issue==='recurring'){replace+=20;reasons.push('A recurring leak requires the full entry path and prior repair history to be traced.')}if(input.issue==='active'){replace+=12;flags.push('Active water: protect people and interiors; avoid the roof and wet electrical areas.')}if(input.issue==='storm'){replace+=15;reasons.push('Storm concern requires condition documentation before scope or coverage conclusions.')}
  if(input.material==='tile'){replace+=8;reasons.push('Tile or slate requires salvage, flashing, underlayment, and structural considerations.')}if(input.slope==='mixed'){replace+=8;reasons.push('Mixed slopes may require more than one compatible roof system.')}if(input.attic==='moisture'){replace+=10;flags.push('Attic moisture can involve air sealing, bath exhaust, insulation, and ventilation—not only roof covering.')}
  replace=Math.min(95,replace);const repair=100-replace;let action=replace>=65?'PLAN REPLACEMENT':replace>=40?'INSPECT + COMPARE':input.issue==='active'||input.issue==='recurring'?'TRACE + REPAIR':'MAINTAIN + MONITOR';if(input.issue==='storm')action='DOCUMENT + INSPECT';
  const scores:Record<string,number>={architectural:62,designer:48,metal:52,membrane:20};
  if(input.slope==='low'){scores.membrane+=75;scores.architectural-=55;scores.designer-=55}else if(input.slope==='mixed'){scores.membrane+=30;scores.metal+=10}else if(input.slope==='steep'){scores.designer+=18;scores.metal+=10}
  if(input.priority==='value')scores.architectural+=28;if(input.priority==='storm'){scores.architectural+=18;scores.metal+=18}if(input.priority==='longevity')scores.metal+=42;if(input.priority==='design')scores.designer+=40;if(input.priority==='efficiency')scores.metal+=30;
  if(input.property==='estate'){scores.designer+=18;scores.metal+=12}if(input.property==='commercial'){scores.membrane+=28;scores.metal+=15;scores.designer-=20}if(input.horizon==='short')scores.architectural+=15;if(input.horizon==='long')scores.metal+=20;
  const systems=systemBase.map((system)=>({...system,score:Math.max(5,Math.min(98,scores[system.id]))})).sort((a,b)=>b.score-a.score);
  const checks=['Deck condition and fastening substrate','Wall, chimney, valley, and penetration flashing','Intake and exhaust ventilation measurements','Drainage path, gutters, and discharge','Exact slope, roof zones, access, and quantities'];if(input.attic==='moisture'||input.attic==='unknown')checks.push('Attic moisture source, exhaust routing, insulation, and air sealing');if(input.issue==='storm')checks.push('Date-linked condition photos and collateral-area observations');if(input.material==='unknown')checks.push('Existing material and assembly identification');
  const confidence=Math.max(58,92-(input.material==='unknown'?10:0)-(input.attic==='unknown'?8:0)-(input.issue==='planning'?4:0));
  return{replace,repair,action,reasons,flags,systems,checks,confidence};
 },[input]);
 const brief=['COWBOY ROOF ADVISOR — PLANNING REPORT',`Roof age: ${input.age} years`,`Current material: ${choices.material.find(x=>x[0]===input.material)?.[1]}`,`Issue: ${choices.issue.find(x=>x[0]===input.issue)?.[1]}`,`Slope: ${choices.slope.find(x=>x[0]===input.slope)?.[1]}`,`Attic signal: ${choices.attic.find(x=>x[0]===input.attic)?.[1]}`,`Property: ${choices.property.find(x=>x[0]===input.property)?.[1]}`,`Priority: ${choices.priority.find(x=>x[0]===input.priority)?.[1]}`,`Ownership horizon: ${choices.horizon.find(x=>x[0]===input.horizon)?.[1]}`,'',`Likely path: ${result.action}`,`Repair signal: ${result.repair}%`,`Replacement signal: ${result.replace}%`,`Primary system match: ${result.systems[0].name}`,'','Field checks:',...result.checks.map(x=>`- ${x}`),'','Planning guidance only. Final diagnosis, scope, code, price, product fit, and damage conditions require field verification.'].join('\n');
 const copy=async()=>{await navigator.clipboard.writeText(brief);setCopied(true)};
 return <>
  <section className="advisor-v2-hero"><div className="shell"><div><p className="eyebrow light">COWBOY ROOF INTELLIGENCE · RULE-BASED</p><h1>More signal.<br/><em>Less guessing.</em></h1><p>Eight roof inputs become an explainable planning report: likely path, repair-versus-replacement signal, ranked systems, red flags, and the exact questions a field inspection still needs to answer.</p><div><a href="#advisor-studio">RUN THE STUDIO ↓</a><Link href="/free-inspection">SKIP TO FIELD INSPECTION</Link></div></div><aside><header><span>ADVISOR STATUS</span><i>READY</i></header><strong>{result.confidence}%</strong><b>INPUT CONFIDENCE</b><p>No camera access · no live code lookup · no price promise · no coverage decision</p><footer><i/> EXPLAINABLE LOGIC ONLY</footer></aside></div></section>
  <section className="advisor-truth"><div className="shell">{[['01','SAFETY FIRST','Urgent hazards override product routing.'],['02','WHY, NOT JUST WHAT','Every recommendation shows its reasoning.'],['03','SYSTEM THINKING','Materials, details, ventilation, and drainage stay connected.'],['04','FIELD TRUTH','Diagnosis and final scope remain on site.']].map(x=><article key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>{x[2]}</span></article>)}</div></section>
  <section id="advisor-studio" className="advisor-studio"><div className="shell"><header><div><p className="eyebrow">THE ROOF DECISION STUDIO</p><h2>Build the signal.</h2></div><p>Change any answer and the report recalculates instantly. Default answers show a representative planning case so the tool is useful before you touch a control.</p></header><div className="advisor-studio-grid">
   <div className="advisor-inputs"><header><span>01 / ROOF INPUTS</span><b>8 SIGNALS</b></header><label className="advisor-slider"><span>APPROXIMATE AGE <b>{input.age} YEARS</b></span><input type="range" min="0" max="40" value={input.age} onChange={e=>update('age',Number(e.target.value))}/><i><small>NEWER</small><small>PLAN + INSPECT</small><small>AGING RANGE</small></i></label>{(Object.keys(choices) as Array<keyof typeof choices>).map((key)=><label key={key}><span>{key==='issue'?'WHAT ARE YOU SEEING?':key==='material'?'CURRENT MATERIAL':key==='slope'?'ROOF SLOPE':key==='attic'?'ATTIC SIGNAL':key==='property'?'PROPERTY TYPE':key==='priority'?'TOP PRIORITY':'OWNERSHIP HORIZON'}</span><div>{choices[key].map(([value,label])=><button type="button" className={input[key]===value?'active':''} aria-pressed={input[key]===value} key={value} onClick={()=>update(key,value)}><i>{input[key]===value?'✓':'→'}</i><b>{label}</b></button>)}</div></label>)}</div>
   <div className="advisor-report"><header><nav>{[['decision','DECISION'],['systems','SYSTEMS'],['brief','FIELD BRIEF']].map(([id,label])=><button type="button" className={view===id?'active':''} onClick={()=>setView(id as typeof view)} key={id}>{label}</button>)}</nav><span><i/> LIVE REPORT</span></header>
    {view==='decision'&&<div className="decision-view"><div className="decision-status"><small>LIKELY PATH</small><h3>{result.action}</h3><span>{result.confidence}% INPUT CONFIDENCE</span></div>{result.flags.length>0&&<div className="advisor-flags">{result.flags.map(flag=><p key={flag}><b>!</b>{flag}</p>)}</div>}<div className="decision-meter"><span><small>REPAIR / MAINTAIN SIGNAL</small><b>{result.repair}%</b><i><em style={{width:`${result.repair}%`}}/></i></span><span><small>REPLACEMENT SIGNAL</small><b>{result.replace}%</b><i><em style={{width:`${result.replace}%`}}/></i></span></div><div className="decision-match"><small>PRIMARY SYSTEM MATCH</small><h3>{result.systems[0].name}</h3><b>{result.systems[0].fit}</b><p>{result.systems[0].copy}</p></div><div className="decision-reasons"><small>WHY THE ADVISOR LEANED THIS WAY</small>{result.reasons.map((reason,index)=><p key={reason}><span>0{index+1}</span>{reason}</p>)}</div></div>}
    {view==='systems'&&<div className="systems-view"><small>RANKED SYSTEM FIT</small><h3>Four paths. One roof-specific order.</h3>{result.systems.map((system,index)=><article key={system.id}><span>0{index+1}</span><div><b>{system.name}</b><small>{system.fit}</small><p>{system.copy}</p><i><em style={{width:`${system.score}%`}}/></i></div><strong>{system.score}%</strong><Link href={system.path}>FILE →</Link></article>)}</div>}
    {view==='brief'&&<div className="brief-view"><small>CREW-READY PLANNING BRIEF</small><h3>What the field still owns.</h3><p>The report is useful because it separates homeowner signals from field-only facts.</p><ol>{result.checks.map((check,index)=><li key={check}><span>{String(index+1).padStart(2,'0')}</span><b>{check}</b><i>VERIFY</i></li>)}</ol><pre>{brief}</pre></div>}
     <footer><div><button type="button" onClick={()=>{try{localStorage.setItem('cowboy-roof-advisor-report',brief);setSaved(true)}catch{setSaved(false)}}}>{saved?'SAVED ON DEVICE ✓':'SAVE REPORT'}</button><button type="button" onClick={copy}>{copied?'COPIED ✓':'COPY BRIEF'}</button></div><a href={`mailto:hello@cowboyroofsupport.com?subject=${encodeURIComponent('My Cowboy Roof Advisor report')}&body=${encodeURIComponent(brief)}`}>EMAIL REPORT →</a><Link href={`/free-inspection?service=${result.replace>=40?'replacement':'general'}&source=advisor`}>FIELD-VERIFY THIS PLAN</Link></footer>
   </div></div></div></section>
  <section className="advisor-assembly-v2"><div className="shell"><header><p className="eyebrow light">THE COMPLETE-ASSEMBLY RULE</p><h2>The finish is only layer six.</h2><p>A roof decision includes airflow, deck and fastening, underlayment, vulnerable-zone water protection, flashing, drainage, and the visible finish.</p></header><div>{[['01','AIR + HEAT','Measure intake, exhaust, moisture sources, insulation, and bath routing.'],['02','DECK + FASTENING','Verify substrate, damaged areas, fastening pattern, edge conditions, and allowances.'],['03','UNDERLAYMENT','Match the underlayment to material, slope, heat, deck, and manufacturer path.'],['04','WATER CONTROL','Detail valleys, eaves, penetrations, walls, kickouts, gutters, and discharge.'],['05','FLASHING','Treat every transition as a designed part of the system—not a leftover.'],['06','FINISH','Choose the visible material only after the assembly and property goals are clear.']].map(x=><article key={x[0]}><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
  <section className="advisor-v2-final"><p className="eyebrow">FROM EXPLAINABLE PLAN TO FIELD TRUTH</p><h2>Let the roof<br/>finish the report.</h2><div><Link href="/free-inspection">START FREE INSPECTION →</Link><Link href="/marketplace">COMPARE SYSTEMS</Link></div></section>
 </>;
}
