'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

type Category = 'Roof systems' | 'Performance' | 'Storm readiness' | 'Field goods';
type Property = 'Home' | 'Estate' | 'Commercial';

type Product = {
  id: string; name: string; edition: string; category: Category; priceLabel: string; unitPrice?: number;
  points: number; description: string; fit: Property[]; priorities: string[]; features: string[];
  finish: string; tone: string; status: string;
};

const products: Product[] = [
  { id: 'ranch', name: 'The Ranch', edition: 'Architectural shingle system', category: 'Roof systems', priceLabel: 'FIELD QUOTE', points: 750, description: 'A complete architectural shingle assembly built around dependable protection, ventilation, and clean curb appeal.', fit: ['Home', 'Estate'], priorities: ['Value', 'Curb appeal', 'Storm'], features: ['Architectural shingles', 'Synthetic underlayment', 'Flashing review', 'Ventilation match'], finish: 'Charcoal ridge', tone: 'charcoal', status: 'CORE SYSTEM' },
  { id: 'blue-ridge', name: 'Blue Ridge', edition: 'Designer shingle system', category: 'Roof systems', priceLabel: 'FIELD QUOTE', points: 1200, description: 'Dimensional designer protection for prominent homes that need stronger shadow lines and estate-level detailing.', fit: ['Home', 'Estate'], priorities: ['Curb appeal', 'Longevity', 'Storm'], features: ['Designer profile', 'Enhanced hip and ridge', 'Complex-detail review', 'Premium finish planning'], finish: 'Slate shadow', tone: 'slate', status: 'DESIGNER SYSTEM' },
  { id: 'stockman', name: 'The Stockman', edition: 'Standing seam metal system', category: 'Roof systems', priceLabel: 'FIELD QUOTE', points: 1800, description: 'A long-life metal path with panel, clip, transition, penetration, edge-metal, and thermal-movement planning.', fit: ['Home', 'Estate', 'Commercial'], priorities: ['Longevity', 'Energy', 'Storm'], features: ['Standing seam panels', 'Concealed fasteners', 'Transition engineering', 'Edge-metal package'], finish: 'Weathered bronze', tone: 'bronze', status: 'LONG-LIFE SYSTEM' },
  { id: 'high-noon', name: 'High Noon', edition: 'Solar-ready roof system', category: 'Roof systems', priceLabel: 'FIELD QUOTE', points: 1600, description: 'A replacement plan that anticipates future solar attachment, wire paths, roof life, ventilation, and penetrations.', fit: ['Home', 'Estate', 'Commercial'], priorities: ['Energy', 'Longevity'], features: ['Solar-ready layout', 'Attachment-zone planning', 'Wire-path coordination', 'Roof-life alignment'], finish: 'Midnight field', tone: 'solar', status: 'ENERGY PATH' },
  { id: 'trail-guard', name: 'Trail Guard', edition: 'Water-barrier package', category: 'Performance', priceLabel: 'FROM $850', points: 150, description: 'Targeted self-adhered protection for vulnerable eaves, valleys, walls, transitions, and penetration zones.', fit: ['Home', 'Estate', 'Commercial'], priorities: ['Storm', 'Longevity'], features: ['Vulnerable-zone map', 'Valley protection', 'Wall transition review', 'Deck-condition check'], finish: 'High-risk zones', tone: 'barrier', status: 'ASSEMBLY UPGRADE' },
  { id: 'air-rider', name: 'Air Rider', edition: 'Ventilation correction', category: 'Performance', priceLabel: 'FROM $1,200', points: 200, description: 'Intake and exhaust planning based on attic volume, obstructions, roof geometry, and moisture signals.', fit: ['Home', 'Estate'], priorities: ['Energy', 'Longevity'], features: ['Intake review', 'Exhaust calculation', 'Attic signal check', 'Balanced-flow plan'], finish: 'Balanced airflow', tone: 'air', status: 'COMFORT UPGRADE' },
  { id: 'rain-boss', name: 'Rain Boss', edition: 'Drainage and gutter system', category: 'Performance', priceLabel: 'FROM $2,400', points: 250, description: 'Gutter, outlet, downspout, discharge, valley-flow, and landscaping coordination as one water-control path.', fit: ['Home', 'Estate', 'Commercial'], priorities: ['Storm', 'Longevity'], features: ['Flow-path review', 'Outlet sizing', 'Downspout routing', 'Discharge planning'], finish: 'Seamless aluminum', tone: 'rain', status: 'WATER CONTROL' },
  { id: 'estate-detail', name: 'Copper Spur', edition: 'Estate-detail package', category: 'Performance', priceLabel: 'FIELD QUOTE', points: 350, description: 'A specialty-detail review for chimneys, crickets, wall transitions, valleys, copper drainage, and ornamental metal.', fit: ['Estate'], priorities: ['Curb appeal', 'Longevity'], features: ['Chimney cricket review', 'Copper detail planning', 'Complex valley map', 'Specialty-metal coordination'], finish: 'Natural copper', tone: 'copper', status: 'ESTATE DETAIL' },
  { id: 'storm-kit', name: 'Storm Ready Kit', edition: 'Homeowner response pack', category: 'Storm readiness', priceLabel: '$59 PROTOTYPE', unitPrice: 59, points: 75, description: 'A homeowner-ready concept pack for safe documentation and temporary interior protection after severe weather.', fit: ['Home', 'Estate'], priorities: ['Storm', 'Value'], features: ['Documentation checklist', 'Interior protection supplies', 'Contact card', 'Safety-first field guide'], finish: 'Safety orange', tone: 'storm', status: 'CONCEPT PRODUCT' },
  { id: 'property-kit', name: 'Property Manager Kit', edition: 'Multi-building response pack', category: 'Storm readiness', priceLabel: '$149 PROTOTYPE', unitPrice: 149, points: 180, description: 'A concept response kit for roof-zone labeling, tenant reports, photo intake, and multi-property storm triage.', fit: ['Commercial'], priorities: ['Storm', 'Value'], features: ['Roof-zone labels', 'Incident intake cards', 'Photo-routing guide', 'Property contact sheet'], finish: 'Command black', tone: 'command', status: 'CONCEPT PRODUCT' },
  { id: 'trail-boss-hat', name: 'Trail Boss Hat', edition: 'Felt hat + copper roof pin', category: 'Field goods', priceLabel: '$125 PROTOTYPE', unitPrice: 125, points: 125, description: 'A premium supporter concept with a structured felt profile and a small copper-tone Cowboy roof pin.', fit: ['Home', 'Estate', 'Commercial'], priorities: ['Field goods'], features: ['Structured felt', 'Copper-tone pin', 'Interior mark', 'Limited-drop concept'], finish: 'Saddle brown', tone: 'hat', status: 'FIELD DROP' },
  { id: 'ridgewalker', name: 'Ridgewalker Boots', edition: 'Western work boot concept', category: 'Field goods', priceLabel: '$189 PROTOTYPE', unitPrice: 189, points: 190, description: 'A western workwear concept designed around early starts, long days, and the Cowboy field identity.', fit: ['Home', 'Estate', 'Commercial'], priorities: ['Field goods'], features: ['Western profile', 'Workwear materials', 'Pull-on design', 'Limited-drop concept'], finish: 'Dark saddle', tone: 'boots', status: 'FIELD DROP' },
  { id: 'high-country-tee', name: 'High Country Tee', edition: 'Heavyweight field tee', category: 'Field goods', priceLabel: '$38 PROTOTYPE', unitPrice: 38, points: 40, description: 'A heavyweight supporter shirt with restrained Cowboy Roof Support field marks and a clean everyday fit.', fit: ['Home', 'Estate', 'Commercial'], priorities: ['Field goods', 'Value'], features: ['Heavyweight cotton', 'Front field mark', 'Back roof trail', 'Prototype sizing'], finish: 'Sunset clay', tone: 'tee', status: 'FIELD DROP' },
  { id: 'roofline-buckle', name: 'Roofline Buckle', edition: 'Numbered brass edition', category: 'Field goods', priceLabel: '$72 PROTOTYPE', unitPrice: 72, points: 75, description: 'A numbered supporter concept built around the roofline, open sky, and understated Cowboy branding.', fit: ['Home', 'Estate', 'Commercial'], priorities: ['Field goods', 'Curb appeal'], features: ['Numbered edition', 'Brass-tone finish', 'Roofline relief', 'Collector concept'], finish: 'Aged brass', tone: 'buckle', status: 'LIMITED CONCEPT' },
];

const categories = ['All', 'Roof systems', 'Performance', 'Storm readiness', 'Field goods'] as const;
const propertyTypes = ['Any property', 'Home', 'Estate', 'Commercial'] as const;
const priorityOptions = ['All goals', 'Value', 'Longevity', 'Storm', 'Energy', 'Curb appeal', 'Field goods'] as const;
const storageKey = 'cowboy-marketplace-build-v2';

export function MarketplaceWorkbench() {
  const [category, setCategory] = useState<(typeof categories)[number]>('All');
  const [property, setProperty] = useState<(typeof propertyTypes)[number]>('Any property');
  const [priority, setPriority] = useState<(typeof priorityOptions)[number]>('All goals');
  const [query, setQuery] = useState('');
  const [selected, setSelected] = useState<string[]>([]);
  const [saved, setSaved] = useState<string[]>([]);
  const [compare, setCompare] = useState<string[]>([]);
  const [detail, setDetail] = useState<string | null>(null);
  const [hydrated, setHydrated] = useState(false);
  const [alertEmail, setAlertEmail] = useState('');
  const [alertReady, setAlertReady] = useState(false);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      try { const current = JSON.parse(window.localStorage.getItem(storageKey) || '[]'); if (Array.isArray(current)) setSelected(current.filter((id) => products.some((product) => product.id === id))); } catch { /* Device saving is optional. */ }
      setHydrated(true);
    }, 0);
    return () => window.clearTimeout(timer);
  }, []);
  useEffect(() => { if (!hydrated) return; try { window.localStorage.setItem(storageKey, JSON.stringify(selected)); } catch { /* Device saving is optional. */ } }, [hydrated, selected]);

  const visible = useMemo(() => products.filter((product) => {
    const text = `${product.name} ${product.edition} ${product.description} ${product.features.join(' ')}`.toLowerCase();
    return (category === 'All' || product.category === category) && (property === 'Any property' || product.fit.includes(property)) && (priority === 'All goals' || product.priorities.includes(priority)) && (!query.trim() || text.includes(query.toLowerCase().trim()));
  }), [category, priority, property, query]);

  const selectedProducts = selected.map((id) => products.find((product) => product.id === id)).filter((product): product is Product => !!product);
  const comparedProducts = compare.map((id) => products.find((product) => product.id === id)).filter((product): product is Product => !!product);
  const detailProduct = products.find((product) => product.id === detail);
  const merchandiseTotal = selectedProducts.reduce((sum, product) => sum + (product.unitPrice || 0), 0);
  const rewardProjection = selectedProducts.reduce((sum, product) => sum + product.points, 0);
  const quoteItems = selectedProducts.filter((product) => !product.unitPrice).length;
  const toggleSelected = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const toggleSaved = (id: string) => setSaved((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const toggleCompare = (id: string) => setCompare((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 3 ? [...current, id] : [current[1], current[2], id]);
  const clearFilters = () => { setCategory('All'); setProperty('Any property'); setPriority('All goals'); setQuery(''); };
  const projectBrief = ['COWBOY MARKETPLACE PROJECT BRIEF', '', ...selectedProducts.map((product, index) => `${index + 1}. ${product.name} — ${product.edition} — ${product.priceLabel}`), '', property === 'Any property' ? '' : `Property: ${property}`, priority === 'All goals' ? '' : `Priority: ${priority}`, merchandiseTotal ? `Prototype merchandise subtotal: $${merchandiseTotal.toLocaleString()}` : '', quoteItems ? `${quoteItems} field-priced item${quoteItems === 1 ? '' : 's'} require inspection and written scope.` : '', `Prototype reward projection: ${rewardProjection.toLocaleString()} points`, '', 'Please help me verify fit, availability, current pricing, and the correct next step.'].filter(Boolean).join('\n');

  return <>
    <section className="marketplace-hero"><div className="shell"><div><p className="eyebrow light">COWBOY MARKETPLACE · SYSTEMS + FIELD GOODS</p><h1>Build the roof.<br/><em>Pack the trail.</em></h1><p>Compare complete roof paths, performance upgrades, storm-readiness concepts, and Cowboy field goods. Save a build on this device, compare three choices, and send one clean project brief.</p><div><a href="#market-workbench">OPEN MARKETPLACE <span>↓</span></a><Link href="/rewards">VIEW REWARD TRAIL</Link></div></div><aside><header><span>MARKET SIGNAL</span><i>LIVE CATALOG</i></header><div><small>ROOF SYSTEMS</small><b>04</b><span>Complete assemblies</span></div><div><small>PERFORMANCE</small><b>04</b><span>Field-scoped upgrades</span></div><div><small>GOODS + READINESS</small><b>06</b><span>Prototype drops</span></div><footer><i/> FIT BEFORE CHECKOUT</footer></aside></div></section>
    <section id="market-workbench" className="market-workbench"><div className="shell">
      <header className="market-workbench-head"><div><p className="eyebrow">THE BUYING WORKBENCH</p><h2>Find what fits.<br/>Then build the list.</h2></div><p>Roof-system prices require a field-verified scope. Merchandise prices and reward values shown here are prototype planning values until the store and program terms launch.</p></header>
      <div className="market-controls"><label><span>SEARCH THE MARKET</span><div><i>⌕</i><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Metal, storm, hat, ventilation…" aria-label="Search marketplace products"/><button type="button" onClick={() => setQuery('')} aria-label="Clear search">×</button></div></label><label><span>PROPERTY</span><select value={property} onChange={(event) => setProperty(event.target.value as typeof property)}>{propertyTypes.map((item) => <option key={item}>{item}</option>)}</select></label><label><span>PRIMARY GOAL</span><select value={priority} onChange={(event) => setPriority(event.target.value as typeof priority)}>{priorityOptions.map((item) => <option key={item}>{item}</option>)}</select></label><div className="market-filter-status"><small>LIVE MATCH</small><b>{visible.length}</b><span>OF {products.length} PRODUCTS</span></div></div>
      <div className="market-category-tabs" role="tablist" aria-label="Marketplace category">{categories.map((item) => <button type="button" role="tab" aria-selected={category === item} className={category === item ? 'active' : ''} key={item} onClick={() => setCategory(item)}><span>{item}</span><small>{item === 'All' ? products.length : products.filter((product) => product.category === item).length}</small></button>)}</div>
      <div className="market-layout"><div className="market-products"><div className="market-results-bar"><span>{visible.length} MATCHES · {property.toUpperCase()} · {priority.toUpperCase()}</span><button type="button" onClick={clearFilters}>RESET FILTERS</button></div>{visible.length ? <div className="market-product-grid">{visible.map((product, index) => { const isSelected = selected.includes(product.id); const isSaved = saved.includes(product.id); const isCompared = compare.includes(product.id); return <article className={isSelected ? 'selected' : ''} key={product.id}><div className={`market-product-visual tone-${product.tone}`}><header><span>{product.status}</span><button type="button" aria-label={`${isSaved ? 'Remove' : 'Save'} ${product.name}`} onClick={() => toggleSaved(product.id)}>{isSaved ? '♥' : '♡'}</button></header><div className="material-signal"><span/><span/><span/></div><footer><small>CRS / {String(index + 1).padStart(2, '0')}</small><b>{product.finish}</b></footer></div><div className="market-product-copy"><small>{product.category} · {product.edition}</small><h3>{product.name}</h3><p>{product.description}</p><div className="market-tags">{product.priorities.slice(0, 3).map((item) => <span key={item}>{item}</span>)}</div><div className="market-price"><span><small>PLANNING PRICE</small><b>{product.priceLabel}</b></span><span><small>REWARD PROJECTION</small><b>+{product.points} PTS</b></span></div><div className="market-card-actions"><button type="button" className={isSelected ? 'added' : ''} onClick={() => toggleSelected(product.id)}>{isSelected ? 'ADDED ✓' : 'ADD TO BUILD +'}</button><button type="button" onClick={() => setDetail(product.id)}>DETAILS</button><button type="button" className={isCompared ? 'compared' : ''} onClick={() => toggleCompare(product.id)}>{isCompared ? 'COMPARE ✓' : 'COMPARE'}</button></div></div></article>; })}</div> : <div className="market-empty"><span>0</span><h3>No exact match yet.</h3><p>Reset the filters or broaden the property and goal. A field inspection can also identify the right assembly when the product name is not obvious.</p><button type="button" onClick={clearFilters}>SHOW THE FULL MARKET →</button></div>}</div>
        <aside className="market-build-panel"><header><div><small>DEVICE-SAVED BUILD</small><h2>Your trail list.</h2></div><span>{selectedProducts.length}</span></header>{selectedProducts.length ? <><div className="market-build-items">{selectedProducts.map((product, index) => <article key={product.id}><small>0{index + 1}</small><div><b>{product.name}</b><span>{product.edition}</span></div><button type="button" onClick={() => toggleSelected(product.id)} aria-label={`Remove ${product.name}`}>×</button></article>)}</div><div className="market-build-math"><span><small>PROTOTYPE GOODS</small><b>${merchandiseTotal.toLocaleString()}</b></span><span><small>FIELD-PRICED ITEMS</small><b>{quoteItems}</b></span><span><small>REWARD PROJECTION</small><b>{rewardProjection.toLocaleString()} PTS</b></span></div><div className="market-build-actions"><a href={`mailto:hello@cowboyroofsupport.com?subject=${encodeURIComponent('My Cowboy Marketplace build')}&body=${encodeURIComponent(projectBrief)}`}>EMAIL THIS BUILD <span>→</span></a><Link href={`/free-inspection?service=${selectedProducts.some((product) => product.category === 'Roof systems') ? 'replacement' : 'general'}&source=marketplace`}>VERIFY WITH FREE INSPECTION</Link><button type="button" onClick={() => setSelected([])}>CLEAR BUILD</button></div></> : <div className="market-build-empty"><span>+</span><h3>Build starts here.</h3><p>Add systems, upgrades, readiness concepts, or field goods. Your list stays on this device until you clear it.</p></div>}<footer><i/> NOTHING IS PURCHASED OR SENT UNTIL YOU CHOOSE A HANDOFF</footer></aside></div>
      {!!comparedProducts.length && <section className="market-compare"><header><div><small>HEAD-TO-HEAD</small><h2>Compare the trail.</h2></div><button type="button" onClick={() => setCompare([])}>CLEAR COMPARISON</button></header><div className={`compare-columns count-${comparedProducts.length}`}>{comparedProducts.map((product) => <article key={product.id}><button type="button" onClick={() => toggleCompare(product.id)} aria-label={`Remove ${product.name} from comparison`}>×</button><small>{product.category}</small><h3>{product.name}</h3><p>{product.edition}</p><dl><div><dt>PLANNING PRICE</dt><dd>{product.priceLabel}</dd></div><div><dt>PROPERTY FIT</dt><dd>{product.fit.join(' · ')}</dd></div><div><dt>BEST FOR</dt><dd>{product.priorities.join(' · ')}</dd></div><div><dt>INCLUDED LOGIC</dt><dd>{product.features.join(' · ')}</dd></div><div><dt>REWARD PROJECTION</dt><dd>+{product.points} points</dd></div></dl><button type="button" onClick={() => toggleSelected(product.id)}>{selected.includes(product.id) ? 'ADDED TO BUILD ✓' : 'ADD TO BUILD →'}</button></article>)}</div></section>}
    </div></section>
    <section className="market-rewards-band"><div className="shell"><div><small>COWBOY REWARD TRAIL</small><h2>Useful actions should earn something.</h2><p>Build a roof plan, complete an inspection, refer a neighbor, or support a field drop. Prototype points show how the future program could connect service and marketplace activity.</p><Link href="/rewards">OPEN THE REWARD WALLET →</Link></div><div className="reward-readout"><span><small>CURRENT BUILD</small><b>{rewardProjection.toLocaleString()}</b><i>PROJECTED POINTS</i></span><span><small>NEXT TIER</small><b>{Math.max(1000 - rewardProjection, 0).toLocaleString()}</b><i>POINTS TO TRAIL BOSS</i></span><footer>PROGRAM RULES + BENEFITS PUBLISH BEFORE LAUNCH</footer></div></div></section>
    <section className="market-alerts"><div className="shell"><div><p className="eyebrow light">OPTIONAL DROP ALERTS</p><h2>New materials.<br/>New field goods.<br/>No clutter.</h2></div><form onSubmit={(event) => { event.preventDefault(); setAlertReady(true); }}><label><span>EMAIL ADDRESS</span><input type="email" value={alertEmail} onChange={(event) => { setAlertEmail(event.target.value); setAlertReady(false); }} required placeholder="you@example.com" autoComplete="email"/></label><button type="submit">{alertReady ? 'ALERT REQUEST READY ✓' : 'PREPARE ALERT REQUEST →'}</button><small>{alertReady ? 'Prototype request prepared. Email delivery will activate only after a notification provider and consent records are configured.' : 'Optional marketing only. Consent is not a condition of purchase. Unsubscribe any time.'} <Link href="/privacy">PRIVACY →</Link></small></form></div></section>
    {detailProduct && <div className="market-detail-modal" role="dialog" aria-modal="true" aria-labelledby="market-detail-title" onMouseDown={(event) => { if (event.currentTarget === event.target) setDetail(null); }}><article><button type="button" className="market-detail-close" onClick={() => setDetail(null)} aria-label="Close product details">×</button><div className={`market-detail-visual tone-${detailProduct.tone}`}><small>{detailProduct.status}</small><div className="material-signal"><span/><span/><span/></div><b>{detailProduct.finish}</b></div><div className="market-detail-copy"><small>{detailProduct.category} · {detailProduct.edition}</small><h2 id="market-detail-title">{detailProduct.name}</h2><p>{detailProduct.description}</p><dl><div><dt>PROPERTY FIT</dt><dd>{detailProduct.fit.join(' · ')}</dd></div><div><dt>BEST FOR</dt><dd>{detailProduct.priorities.join(' · ')}</dd></div><div><dt>PLANNING PRICE</dt><dd>{detailProduct.priceLabel}</dd></div></dl><h3>WHAT THE PLAN CONSIDERS</h3><ul>{detailProduct.features.map((feature) => <li key={feature}><span>✓</span>{feature}</li>)}</ul><div><button type="button" onClick={() => toggleSelected(detailProduct.id)}>{selected.includes(detailProduct.id) ? 'REMOVE FROM BUILD' : 'ADD TO BUILD'} <span>→</span></button><Link href="/free-inspection">VERIFY FIT WITH AN INSPECTION</Link></div><footer>Availability, final price, product specifications, reward eligibility, and roof-system fit must be confirmed before purchase or installation.</footer></div></article></div>}
  </>;
}
