import type { Metadata } from 'next';
import Link from 'next/link';
import { TransformationGallery } from '../components/TransformationGallery';

export const metadata: Metadata = { title: 'Luxury Roof Transformations', description: 'Interactive mansion and luxury-home roof transformation concepts for premium shingles, standing seam metal, and slate-look systems.' };

export default function TransformationsPage() {
  return <main className="transformations-page"><section className="transformation-hero"><div className="shell"><div><p className="eyebrow light">THE TRANSFORMATION HANGAR</p><h1>Big homes.<br/>Every roof detail.</h1></div><p>Drag through mansion-scale roof concepts, then open the technical file behind each system. These visuals demonstrate design and planning capability; they are not presented as completed customer projects.</p></div></section><section className="transformation-gallery-section shell"><TransformationGallery /></section><section className="transformation-files"><div className="shell"><header><p className="eyebrow light">OPEN THE PROJECT FILES</p><h2>The finish is only<br/>the visible layer.</h2></header><div>{[['01','ESTATE ROOF PLANNING','Geometry, staging, protection, documentation, and high-detail closeout.','/library/estate-roof-planning'],['02','STANDING SEAM METAL','Panels, clips, transitions, thermal movement, and penetration details.','/library/standing-seam-metal'],['03','DESIGNER SHINGLES','Profile, shadow line, valley strategy, flashing, and color coordination.','/library/designer-shingles'],['04','QUALITY STANDARD','The checkpoints and proof trail behind every serious roof plan.','/quality']].map(([n,title,copy,href]) => <Link href={href} key={href}><small>{n}</small><h3>{title}</h3><p>{copy}</p><b>OPEN FILE →</b></Link>)}</div></div></section><section className="final-cta"><p className="eyebrow">YOUR PROPERTY · YOUR SYSTEM</p><h2>Build the right brief.</h2><Link className="primary" href="/free-inspection">REQUEST A FREE INSPECTION <span>→</span></Link></section></main>;
}
