'use client';
import { FormEvent, useState } from 'react';

const services = [
  ['01','Roof Replacement','A complete roofing system built around your home, budget, and Georgia weather.','⌂'],
  ['02','Storm Damage','Fast assessment, clear photo documentation, and a practical restoration plan.','↯'],
  ['03','Repairs & Leaks','Targeted repairs for shingles, flashing, vents, valleys, and hidden trouble spots.','◆'],
  ['04','Metal Roofing','Long-lasting standing seam systems with premium finishes and serious curb appeal.','▥'],
];
const areas=['Alpharetta','Roswell','Milton','Johns Creek','Cumming','Woodstock'];

export default function Home(){
 const [open,setOpen]=useState(false); const [sent,setSent]=useState(false);
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSent(true)};
 return <main>
  <div className="topline"><span>North Atlanta’s straight-shooting roof crew</span><a href="#estimate">Free roof assessment →</a></div>
  <header><a className="brand" href="#top"><span className="mark">C</span><span><b>COWBOY</b><small>ROOF SUPPORT</small></span></a><button className="menu" onClick={()=>setOpen(!open)}>{open?'×':'☰'}</button><nav className={open?'open':''}>{[['#services','Services'],['#standard','Our standard'],['#process','Process'],['#areas','Service area']].map(x=><a key={x[0]} href={x[0]} onClick={()=>setOpen(false)}>{x[1]}</a>)}</nav><a className="headerCta" href="#estimate">Get a free estimate ↗</a></header>
  <section className="hero" id="top"><div className="heroBg"/><div className="shade"/><div className="heroCopy"><p className="eyebrow">✦ ROOFED RIGHT. COWBOY BUILT.</p><h1>We ride for<br/>the <em>roofline.</em></h1><p>Premium roofing, honest answers, and a crew that shows up. Built for North Atlanta homes—and whatever the Georgia sky throws their way.</p><div className="actions"><a href="#estimate">Get my free assessment →</a><a href="#services">Explore our work</a></div><div className="proof"><span><b>LOCAL</b>North Atlanta crew</span><span><b>THOROUGH</b>Photo-documented inspections</span><span><b>BUILT TO LAST</b>Complete roof systems</span></div></div><div className="stamp">✦<b>STAND<br/>TALL</b><small>UNDER EVERY ROOF</small></div></section>
  <section className="services" id="services"><div className="intro"><div><p className="eyebrow rust">WHAT WE DO</p><h2>Every roof has a story.<br/><em>We make yours a good one.</em></h2></div><p>From the first shingle to the final nail sweep, we keep the process clear, the property respected, and the workmanship sharp.</p></div><div className="serviceGrid">{services.map(s=><article key={s[1]}><div><small>{s[0]}</small><i>{s[3]}</i></div><h3>{s[1]}</h3><p>{s[2]}</p><a href="#estimate">Talk to the crew ↗</a></article>)}</div></section>
  <section className="standard" id="standard"><div className="westernArt"><div className="sun"/><div className="roof"/><p>COWBOY COUNTRY<br/><b>NORTH ATLANTA, GA</b></p></div><div className="standardCopy"><p className="eyebrow">THE COWBOY STANDARD</p><h2>No runaround.<br/><em>No loose ends.</em></h2><p>Good roofing is more than what happens on top of the house. It’s the phone call returned, the landscaping protected, the scope explained, and the site left cleaner than we found it.</p><ul><li><span>01</span>Clear recommendations before work begins</li><li><span>02</span>A complete system—not a pile of shingles</li><li><span>03</span>Respect for your home and schedule</li><li><span>04</span>A final walkthrough with nothing unclear</li></ul><a href="#estimate">Put the Cowboy Standard on my roof →</a></div></section>
  <section className="process" id="process"><p className="eyebrow rust">HOW IT WORKS</p><h2>Four steps. <em>One solid roof.</em></h2><div className="steps">{[['01','The Look','We inspect the roof, attic, flashing, drainage, and ventilation.'],['02','The Plan','You get clear findings, photos, choices, and a straightforward scope.'],['03','The Build','Our crew protects the property and installs your complete system.'],['04','The Handshake','We clean up, walk the job, and make sure every detail lands right.']].map(s=><article key={s[0]}><span>{s[0]}</span><div><h3>{s[1]}</h3><p>{s[2]}</p></div></article>)}</div></section>
  <section className="areas" id="areas"><div><p className="eyebrow">OUR HOME RANGE</p><h2>Built for Georgia.<br/><em>Based in North Atlanta.</em></h2><p>Local knowledge matters—from summer heat and hard rain to wind that arrives without warning.</p></div><div className="areaList">{areas.map((a,i)=><span key={a}><small>0{i+1}</small>{a}<b>↗</b></span>)}</div></section>
  <section className="estimate" id="estimate"><div><p className="eyebrow">START HERE</p><h2>Let’s put a strong roof<br/><em>over your story.</em></h2><p>Tell us what’s happening. We’ll start with a clear conversation and help you choose the right next step.</p></div><form onSubmit={submit}>{sent?<div className="success"><span>✓</span><h3>We’ll take it from here, partner.</h3><p>Your request is ready for the Cowboy crew.</p><button type="button" onClick={()=>setSent(false)}>Send another request</button></div>:<><div className="row"><label>YOUR NAME<input required placeholder="First and last name"/></label><label>PHONE NUMBER<input required type="tel" placeholder="(555) 000-0000"/></label></div><label>EMAIL ADDRESS<input required type="email" placeholder="you@example.com"/></label><label>WHAT CAN WE HELP WITH?<select required defaultValue=""><option value="" disabled>Choose a service</option><option>Roof replacement</option><option>Storm damage</option><option>Roof repair or leak</option><option>Metal roofing</option><option>Not sure yet</option></select></label><label>PROJECT DETAILS<textarea placeholder="Tell us what you’re seeing and your city."/></label><button className="submit">Request my free assessment →</button><small>No pressure. Just a clear next step for your roof.</small></>}</form></section>
  <footer><div><a className="brand" href="#top"><span className="mark">C</span><span><b>COWBOY</b><small>ROOF SUPPORT</small></span></a><p>Premium roofing. Straight-shooting service.<br/>Proudly serving North Atlanta.</p></div><div><b>EXPLORE</b><a href="#services">Services</a><a href="#standard">Our standard</a><a href="#process">Process</a></div><div><b>HOME RANGE</b>{areas.slice(0,4).map(a=><a href="#areas" key={a}>{a}</a>)}</div><a className="footerCta" href="#estimate"><span>READY WHEN<br/>YOU ARE</span><b>LET’S RIDE ↗</b></a><p className="copy">© 2026 Cowboy Roof Support <span>Roofed right. Cowboy built.</span></p></footer>
 </main>
}
