import Link from 'next/link';

export default function Home() {
  return <main>
    <section className="home-hero">
      <div className="hero-copy"><p className="eyebrow">COWBOY ROOF OS · NORTH ATLANTA</p><h1>A better roof.<br/><em>Built intelligently.</em></h1><p>Expert material logic, context-aware guidance, and a hands-on crew. Every tool has one job—and every button takes you to the useful next step.</p><div className="actions"><Link className="primary" href="/roof-advisor">RUN ROOF ADVISOR <span>→</span></Link><Link className="text-link" href="/start">START A PROJECT</Link></div><div className="hero-signals"><span><i/>ROOF COPILOT ONLINE</span><span>6 FACTORS</span><span>9 CLEAR SECTIONS</span></div></div>
      <div className="hero-architecture"><div className="arch-label"><span>01 / ROOF DIGITAL TWIN</span><span>INTERACTIVE PLANNING</span></div><div className="house-art"><span className="sun"/><span className="roof-plane one"/><span className="roof-plane two"/><span className="house-block"><i/><i/><i/></span><b>SYSTEM STATUS · READY</b></div><div className="arch-data"><span><small>SMART MATCH</small>CLASS 4 SYSTEM</span><span><small>REGION</small>NORTH ATLANTA</span><Link href="/customize">CONFIGURE SYSTEM ↗</Link></div></div>
    </section>
    <section className="promise-strip"><span>FREE INSPECTION</span><i>✦</i><span>SMART ROOF ADVISOR</span><i>✦</i><span>PREMIUM MATERIAL SYSTEMS</span><i>✦</i><span>COWBOY FOLLOW-THROUGH</span></section>
    <section className="spend-paths shell"><div className="spend-head"><p className="eyebrow">WHAT DO YOU NEED TODAY?</p><h2>One click. Right trail.</h2></div><div>{[['⌂','START A ROOF PROJECT','Leak, storm, replacement, metal, or commercial','/start'],['◇','GET A FREE INSPECTION','Put real eyes on the roof before making the big decision','/services#inspection'],['▦','COMPARE ROOF SYSTEMS','Choose materials, colors, upgrades, and a planning range','/customize'],['✦','SHOP THE MARKETPLACE','Build a list of roof upgrades, gear, hats, and boots','/marketplace']].map(x=><Link key={x[1]} href={x[3]}><i>{x[0]}</i><span><b>{x[1]}</b><small>{x[2]}</small></span><strong>→</strong></Link>)}</div></section>
    <section className="expert-teaser shell"><div><p className="eyebrow light">COWBOY ROOF INTELLIGENCE</p><h2>Concise inputs.<br/>Useful outputs.</h2><p>Age, symptoms, slope, attic, tree cover, and priorities stay in their own modules—then combine into one system recommendation.</p><Link href="/roof-advisor">RUN ROOF ANALYSIS →</Link></div><div className="teaser-readout"><span><small>01 / ROOF SIGNAL</small>PLANNING AHEAD</span><span><small>02 / SYSTEM MATCH</small>CLASS 4 ASSEMBLY</span><span><small>03 / CLIMATE LOGIC</small>HEAT · WIND · RAIN</span><b><i/> COPILOT READY</b></div></section>
    <section className="home-quality"><div className="home-quality-photo"><img src="/cowboy-crew-v1.png" alt="Friendly Cowboy Roof Support crew speaking with a homeowner"/><span>THE KIND OF CREW YOU WANT AT YOUR HOUSE</span></div><div className="home-quality-copy"><p className="eyebrow light">QUALITY, PROTECTION, AND ACTUAL PEOPLE</p><h2>Nice people.<br/>Serious roofs.</h2><p>Documented checkpoints, property protection, honest insurance information, and friendly humans who explain the job without the roofing riddles.</p><blockquote>“We save the tall tales for the campfire.”</blockquote><Link href="/quality">SEE THE COWBOY QUALITY STANDARD →</Link></div></section>
    <section className="route-section shell"><div className="section-intro"><p className="eyebrow">ONE CLEAR PLACE FOR EVERY JOB</p><h2>Choose your trail.</h2><p>The old one-page site is now divided into focused sections. Go deep when you want detail. Get answers fast when you do not.</p></div><div className="route-grid">
      <Link className="route-card dark-card" href="/customize"><span>01</span><small>INTERACTIVE TOOL</small><h3>Customize<br/>your roof.</h3><p>Shape, size, materials, colors, upgrades, blueprint, and a live planning range.</p><b>START BUILDING →</b></Link>
      <Link className="route-card blueprint-card" href="/guides"><span>02</span><small>KNOW YOUR SYSTEM</small><h3>Blueprints<br/>& easy guides.</h3><div className="mini-blueprint"><i/><i/><i/></div><b>LEARN THE ROOF →</b></Link>
      <Link className="route-card copper-card" href="/marketplace"><span>03</span><small>ROOF + FIELD GOODS</small><h3>Shop the<br/>marketplace.</h3><p>Roof systems, upgrades, storm gear, hats, boots, and limited drops.</p><b>ENTER MARKETPLACE →</b></Link>
    </div></section>
    <section className="scale-section"><div className="scale-copy"><p className="eyebrow light">HOME ROOFS COME FIRST</p><h2>Small enough to care.<br/>Built to go big.</h2><p>Replacement, repair, ventilation, gutters, storm response—and dedicated planning for complex commercial roofs, high-rises, arenas, and large properties.</p><Link className="outline-light" href="/services">SEE EVERY CAPABILITY →</Link></div><div className="skyline-art"><span/><span/><span/><i/><b>HOME → COMPLEX → SKYLINE</b></div></section>
    <section className="final-cta"><p className="eyebrow">YOUR ROOF. YOUR PLAN.</p><h2>Ready to build it?</h2><Link className="primary" href="/customize">OPEN THE CONFIGURATOR <span>→</span></Link></section>
  </main>;
}
