'use client';
import { useState } from 'react';

const products = [
  ['The Ranch','Roof systems','Architectural shingle','$$','charcoal'],['Blue Ridge','Roof systems','Designer shingle','$$$','slate'],['The Stockman','Roof systems','Standing seam metal','$$$$','metal'],['High Noon','Roof systems','Solar-ready system','$$$$','solar'],
  ['Trail Guard','Performance','Water barrier package','From $850','barrier'],['Air Rider','Performance','Ventilation upgrade','From $1,200','air'],['Rain Boss','Performance','Seamless gutter system','From $2,400','rain'],['Storm Kit','Performance','Homeowner storm gear','$59','storm'],
  ['Trail Boss Hat','Field goods','Felt hat + copper roof pin','$125','hat'],['Ridgewalker Boots','Field goods','Western work boot','$189','boots'],['High Country Tee','Field goods','Heavyweight field tee','$38','tee'],['Roofline Buckle','Field goods','Numbered brass edition','$72','buckle'],
];
export default function Marketplace(){const [filter,setFilter]=useState('All');const [saved,setSaved]=useState<string[]>([]);const visible=filter==='All'?products:products.filter(p=>p[1]===filter);return <main><section className="page-hero market-hero"><div><p className="eyebrow light">THE COWBOY MARKETPLACE</p><h1>Roof systems.<br/>Field goods.</h1></div><p>Compare the systems that protect your home. Find the upgrades that make them work harder. Grab the gear that carries the brand beyond the roof.</p></section><section className="market-shell shell"><div className="market-toolbar"><div>{['All','Roof systems','Performance','Field goods'].map(x=><button className={filter===x?'selected':''} key={x} onClick={()=>setFilter(x)}>{x}</button>)}</div><span>{visible.length} PRODUCTS · {saved.length} SAVED</span></div><div className="catalog-grid">{visible.map(p=><article key={p[0]}><div className={`catalog-art ${p[4]}`}><span/><button onClick={()=>setSaved(s=>s.includes(p[0])?s.filter(x=>x!==p[0]):[...s,p[0]])}>{saved.includes(p[0])?'♥':'♡'}</button><small>{p[3]}</small></div><div className="catalog-info"><small>{p[1]} / {p[2]}</small><h2>{p[0]}</h2><p>{p[1]==='Field goods'?'Built for early starts, long days, and Cowboy supporters.':'A field-reviewed option available to add to your project plan.'}</p><button>{p[1]==='Field goods'?'VIEW DROP':'ADD TO ROOF PLAN'} →</button></div></article>)}</div></section><section className="market-banner"><span>NEW DROPS</span><h2>Roof alerts. Gear drops. No clutter.</h2><form onSubmit={(e)=>e.preventDefault()}><input type="email" required placeholder="EMAIL ADDRESS"/><button>JOIN THE LIST →</button></form><small>Prototype signup—delivery will connect when the notification service is configured.</small></section></main>}
