import type { Metadata } from 'next';
import Link from 'next/link';
import { ReferralStudio } from '../components/ReferralStudio';

export const metadata: Metadata = { title: 'Family Share Desk', description: 'One-tap organic Facebook sharing and referral tools for Cowboy Roof Support.' };

export default function SharePage() {
  return <main className="share-page"><section className="share-hero"><div className="shell"><div><p className="eyebrow light">THE ORGANIC ACQUISITION DESK</p><h1>Turn local trust<br/>into a clean trail.</h1></div><p>Build a different link for every family member, city, neighborhood group, and roof concern. The homeowner gets a focused page and the source stays attached to the prepared inspection brief.</p></div></section><section className="share-workbench shell"><header><p className="eyebrow">NO AD SPEND REQUIRED</p><h2>Build. Post. Track.</h2><p>Choose who is sharing, where the homeowner lives, and what prompted the post. The desk creates the link, landing page, starting service, and ready-to-copy wording.</p></header><ReferralStudio /></section><section className="organic-cadence shell"><header><p className="eyebrow">THE 7-DAY ORGANIC LOOP</p><h2>Stay useful.<br/>Stay visible.</h2></header><div>{[['DAY 01','PERSONAL INTRO','Tell people who the family team is and why you trust them.'],['DAY 02','ROOF TIP','Post one useful roof or safety observation without selling.'],['DAY 03','LOCAL PAGE','Share a city-specific roof-check link in the relevant group.'],['DAY 04','QUESTION','Ask what roof problem neighbors find hardest to understand.'],['DAY 05','MATERIAL GUIDE','Share one technical file from the roofing library.'],['DAY 06','STORM READINESS','Explain safe documentation and when not to climb.'],['DAY 07','SOFT REMINDER','Repost the short link with a simple invitation to ask.']].map(([day,title,copy]) => <article key={day}><small>{day}</small><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="share-rules"><div className="shell">{[['01','BE PERSONAL','A real introduction from someone neighbors know will outperform generic sales copy.'],['02','BE USEFUL','Lead with the roof problem, safety, and a clear next step—not pressure.'],['03','BE CONSISTENT','Reuse each campaign link so responses follow a measurable source trail.'],['04','FOLLOW UP FAST','A warm lead cools quickly. Call or email as soon as the prepared request arrives.']].map(([n,title,copy]) => <article key={n}><small>{n}</small><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="share-next"><div><p className="eyebrow light">RUN THE WHOLE SYSTEM</p><h2>Open Growth Command.</h2></div><div className="share-next-actions"><Link href="/growth">OPEN GROWTH COMMAND CENTER →</Link><Link href="/neighbors?ref=family-facebook&utm_source=facebook&utm_medium=organic_social&utm_campaign=north-atlanta_general&service=general">PREVIEW CUSTOMER TRAIL →</Link></div></section></main>;
}
